version: '3.9'
services:
  mongo:
    container_name: hsa3_mongo
    image: mongo:6.0.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=hsa3
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    restart: always
  
  elastic:
    container_name: hsa3_elastic
    image: elasticsearch:7.17.16
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    env_file: elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app_network

  app:
    container_name: hsa3_web
    build: ./application
    working_dir: /application
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/?authSource=admin
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./application:/application:rw
    depends_on:
      - mongo
      - elastic
    ports:
      - 8000:8000
    networks:
      - app_network
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  nginx:
    container_name: hsa3_nginx
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
      - '8081:81'
    depends_on:
      - app
      # - grafana
    networks:
      - app_network

volumes:
  mongodb_data: {}
  elastic_data: {}

networks:
  app_network:
    driver: bridge
