version: '3.9'
services:
  mongo:
    container_name: hsa3_mongo
    image: mongo:6.0.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=hsa3
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
    networks:
      - app_network
    restart: always
  
  elastic:
    container_name: hsa3_elastic
    image: elasticsearch:7.17.16
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    env_file: elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app_network

  app:
    container_name: hsa3_web
    build: ./application
    working_dir: /application
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/?authSource=admin
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./application:/application:rw
    depends_on:
      - mongo
      - elastic
    ports:
      - 8000:8000
    networks:
      - app_network
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  nginx:
    container_name: hsa3_nginx
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
      - '8081:81'
    depends_on:
      - app
      # - grafana
    networks:
      - app_network

  influxdb:
    container_name: hsa3_influxdb
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - app_network

  telegraf:
    container_name: hsa3_telegraf
    image: telegraf:1.27
    restart: unless-stopped
    user: root
    entrypoint: telegraf
    environment:
      - MONGO_URI=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo/?authSource=admin&connect=direct
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - nginx
      - influxdb
    networks:
      - app_network

  grafana:
    container_name: hsa3_grafana
    image: grafana/grafana:10.3.1
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - app_network

  siege:
    container_name: hsa3_siege
    build: ./siege
    working_dir: /siege
    volumes:
      - ./siege:/siege:rw
      - ./siege/siege.conf:/root/.siege/siege.conf:ro
    links:
      - nginx
      - app
    depends_on:
      - nginx
      - telegraf
    networks:
      - app_network
    command: sh siege.sh

volumes:
  mongodb_data: {}
  elastic_data: {}
  grafana_data: {}
  influxdb_data: {}

networks:
  app_network:
    driver: bridge
